INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (2, 'CPR Certification', 'Local classes held at convenient locations and times which allow you to participate in hands-on training. You will learn from experienced instructors and receive full certification.
', '2019-07-12', 'The Adult and Pediatric First Aid/CPR/AED course incorporates the latest science and teaches students to recognize and care for a variety of first aid emergencies such as burns, cuts, scrapes, sudden illnesses, head, neck, back injuries, heat and cold emergencies and how to respond to breathing and cardiac emergencies to help victims of any age - adults (about 12 years and older) and pediatric (infants and children up to 12 years of age). Students who successfully complete this course will receive a certificate for Adult and Pediatric First Aid/CPR/AED valid for two years.', 'You will learn to do CPR', 'CPR Class', '2019-07-12', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (3, 'EMT Certification', 'This course is the required course for any person seeking to become a state certified Emergency Medical Technician - Basic (EMT-B). The course is based on the Department of Transportation''s (DOT) 1994 EMT-Basic curriculum. This course has been developed for individuals who desire to perform emergency medical care.', '2019-07-26', 'Emergency Medical Technicians provide out of hospital emergency medical care and transportation for critical and emergent patients who access the emergency medical services (EMS) system. EMTs have the basic knowledge and skills necessary to stabilize and safely transport patients ranging from non-emergency and routine medical transports to life threatening emergencies. Emergency Medical Technicians function as part of a comprehensive EMS response system, under medical oversight. Emergency Medical Technicians perform interventions with the basic equipment typically found on an ambulance. Emergency Medical Technicians are a critical link between the scene of an emergency and the health care system. ', 'You will learn to become an EMT', 'EMT Class', '2019-07-12', 2, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (4, 'EMR Certification', 'You will learn the basics of teh EMR course.', '2019-07-10', 'Emergency Medical Responders provide immediate lifesaving care to critical patients who access the emergency medical services system. EMRs have the knowledge and skills necessary to provide immediate lifesaving interventions while awaiting additional EMS resources to arrive. EMRs also provide assistance to higher-level personnel at the scene of emergencies and during transport. Emergency Medical Responders are a vital part of the comprehensive EMS response. Under medical oversight, Emergency Medical Responders perform basic interventions with minimal equipment. ', 'You will learn to become a EMR', 'EMR Class', '2019-07-12', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (5, 'AEMT Certification', 'This course is to prepare you for the live of a AEMT.', '2019-07-03', 'The primary focus of the Advanced Emergency Medical Technician is to provide basic and limited advanced emergency medical care and transportation for critical and emergent patients who access the emergency medical system. This individual possesses the basic knowledge and skills necessary to provide patient care and transportation. Advanced Emergency Medical Technicians function as part of a comprehensive EMS response, under medical oversight. Advanced Emergency Medical Technicians perform interventions with the basic and advanced equipment typically found on an ambulance. The Advanced Emergency Medical Technician is a link from the scene to the emergency health care system. ', 'You will learn to be a AEMT', 'AEMT CLass', '2019-07-12', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (1011, 'eligible for employment with immediate full peace officer status by law enforcement agencies in the State of Texas.', 'The Nature and Extent of Delinquency and Conduct in Need of Supervision
Philosophy of Juvenile System
Organization, processes and functions of the juvenile justice system in the United States and Texas
Extent of offense committed by children and the impact on society', '2019-07-16', 'This course is a study of the juvenile justice process.  Topics include specialized juvenile law, role of the juvenile law, role of the juvenile courts, role of police agencies, role of correctional agencies, and theories concerning delinquency.  In addition, students will study the history, philosophy, organization, processes and functions of the juvenile justice systems in the United States and Texas.  Emphasis is placed on jurisdiction, treatment and juvenile court proceedings in juvenile justice decision-making.  In addition, students will study child abuse and neglect and how the system is designed to deal with these serious issues.', 'Students will have a working knowledge of the Texas Family Code governing delinquent conduct and conduct indicating a need for supervision.  Students will be able to define the role and functions of law enforcement officer, juvenile probation officer, and the juvenile court in investigating and handling cases involving a child and persons coming under the jurisdiction of the juvenile justice system. Students will be able to list and/or describe juvenile correction processes include treatment, rehabilitation, and sanctions administered under the Juvenile Justice System that seek to correct children’s conduct that adversely threatens or harms the community.  Students will also be able to describe the laws relative to child abuse and neglect and understand systems’ response to protect children.', 'Academic Alternative Course', '2005-02-16', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (1013, 'Telecommunicator’s Certification', 'The Basic Telecommunicator Certification Course is designed to provide the beginning Telecommunicator with an understanding of situations encountered in an emergency communications environment and the basic skills necessary to collect information in both emergency and non-emergency situations. This course is required by the Commission for certification.', '2009-07-14', 'The Basic Telecommunicator Certification Course is designed to provide the beginning Telecommunicator with an understanding of situations encountered in an emergency communications environment and the basic skills necessary to collect information in both emergency and non-emergency situations. This course is required by the Commission for certification.', 'The student will be able to summarize some issues involving the Telecommunicator’s role and responsibilities as a member of public safety.', 'Basic Telecommunications', '2014-02-14', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (1018, 'Course(1018) Certificate of Completion', null, '2019-07-16', null, null, 'Supplemental Peace Officer', '2014-10-15', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (1030, 'Course(1030) Certificate of Completion', null, '1996-07-10', null, null, 'Special Forces Veterans', '2016-11-16', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (1107, 'Course(1107) Certificate of Completion', null, '1996-07-10', null, null, 'Basic Jail Certification Course for Sworn Texas Peace Officers', '2017-09-19', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (1120, 'Course(1120) Certificate of Completion', null, '1996-07-10', null, null, '2018 Basic County Corrections Course', '2001-03-07', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (1849, 'Course(1849) Certificate of Completion', null, '1996-07-10', null, null, 'De-escalation Techniques: Limiting the use of Force in Public Interaction', '2019-10-22', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (1850, 'Crisis Intervention Certificate of Completion', null, '1996-07-10', null, null, 'Crisis Intervention Training', '2013-05-09', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (3184, 'Course(3184) Certificate of Completion', null, '1996-07-10', null, null, 'State and Federal Law Update (Course 3184)', '2001-01-03', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (3185, 'Course(3185) Certificate of Completion', null, '1996-07-10', null, null, 'State and Federal Law Update (Course 3185)', '2015-11-21', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (3232, 'Course(3232) Certificate of Completion', null, '1996-07-10', null, null, 'Special Investigative Topics', '2005-02-11', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (3255, 'Course(3255) Certificate of Completion', null, '1996-07-10', null, null, 'Asset Forfeiture', '2018-11-20', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (3256, 'Racial Profiling Certificate of Completion', null, '1996-07-10', null, null, 'Racial Profiling', '2013-10-15', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (3270, 'Human Trafficking Certificate of Completion', null, '1996-07-10', null, null, 'Human Trafficking', '2016-07-07', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (3277, 'Identify Theft Crimes Certificate of Completion', null, '1996-07-10', null, null, 'Identity Theft Crimes', '2003-09-03', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (3286, 'Course(3286) Certificate of Completion', null, '1996-07-10', null, null, 'Eyewitness Evidence/Identification', '2018-01-01', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (7878, 'Course(7878) Certificate of Completion', null, '1996-07-10', null, null, 'Peace Officer Reactivation Physical Skills Assessment', '2019-07-11', 1, null);
INSERT INTO training_db.curriculum (id, certification, course_outline, creation_date, description, learning_objectives, name, update_date, provider_id, capacity) VALUES (1000643, 'Basic Peace Officer Certificate of Completion', null, '1996-07-10', null, null, 'Basic Peace Officer', '2017-10-17', 1, null);